name: ghcr.io Repository Cleanup Action

description: >
  Delete obsolete images from a repository in the GitHub Container Registry
  (ghcr.io).

author: Jens Keiner

branding:
  icon: trash-2
  color: red

inputs:
  token:
    description: >
      Token to authenticate with the ghcr.io registry and the GitHub API
    required: true

  owner:
    description: >
      Owner of the package (user or organization)
    required: false

  repository:
    description: >
      The GitHub repository where the package is stored. Defaults to repository
      name.
    required: false

  package:
    description: >
      The package name. Defaults to the repository name.
    required: false

  include-tags:
    description: >
      Regular expression that matches tags to delete
    required: false

  exclude-tags:
    description: >
      Regular expression that matches tags to keep
    required: false

  keep-n-tagged:
    description: >
      Number of most recent tagged images to keep
    required: false

  keep-n-untagged:
    description: >
      Number of most recent untagged images to keep
    required: false

  dry-run:
    description: >
      Simulate action, do not actually remove any packages
    required: false

  log-level:
    description: >
      Log level (error/warn/info/debug)
    default: warn

runs:
  using: node20
  main: dist/index.js
