name: Ghcr.io Cleanup Action

description: >
  Delete untagged/tagged images from the GitHub Container Registry. Supports
  multi-architecture and attestation images.

author: Dataaxiom Inc

branding:
  icon: trash-2
  color: green

inputs:
  # General Options
  token:
    description: >
      Token to authenticate with the ghcr.io registry and the GitHub API
    required: true
    default: ${{ github.token }}

  owner:
    description: >
      Owner of the package (user or organization). Defaults to project owner
    required: false

  repository:
    description: >
      The GitHub repository where the package is stored. Defaults to repository
      name
    required: false

  package:
    description: >
      Comma-separated list of packages to cleanup. Support dynamic packages
      (wildcard or regular expression) by enabling the expand-packages option.
    required: false

  packages:
    description: >
      Alternative name for package option
    required: false

  expand-packages:
    description: >
      Enable wildcard or regular expression support on the package(s) option to
      support dynamic package selection. Requires use of a Personal Access Token
      (PAT) for the token value.
    required: false

  # Cleanup Options

  delete-tags:
    description: >
      Comma-separated list of tags to delete (supports wildcard syntax), can be
      abbreviated as `tags`. A regular expression selector can be used instead
      by setting the `use-regex` option to true
    required: false

  tags:
    description: >
      Short form of `delete-tags` input option
    required: false

  exclude-tags:
    description: >
      Comma-separated list of tags strictly to be preserved/excluded from
      deletion (supports wildcard syntax). A regular expression selector can be
      used instead by setting the `use-regex` option to true
    required: false

  keep-n-untagged:
    description: >
      Number of untagged images to keep (sorted by date, keeping newest)
    required: false

  keep-n-tagged:
    description: >
      Number of tagged images to keep (sorted by date, keeping newest)
    required: false

  delete-untagged:
    description: >
      Delete all untagged images. This option is set to true when no other
      delete or keep options are set (true/false)
    required: false

  delete-ghost-images:
    description: >
      Delete multi architecture images where all underlying platform images are
      missing (true/false) Default: false
    required: false

  delete-partial-images:
    description: >
      Delete multi architecture images where some (but not all) underlying
      platform images are missing (true/false) Default: false
    required: false

  delete-orphaned-images:
    description: >
      Delete orphaned images (referrers/cosign etc) where the parent image
      doesn't exist. Uses a tagged based check.
    required: false

  older-than:
    description: >
      Only include packages for processing that are older than this value. Use
      the following format samples: 50 seconds, 15 days, 6 months, 2 years
    required: false

  # Additional Options

  use-regex:
    description: >
      Use a regex expression in place of wildcard matcher for package,
      delete-tags and exclude-tags options (true/false) Default: false
    required: false

  validate:
    description: >
      Validate all multi-architecture images manifests by checking their digests
      are present in the registry (true/false) Default: false
    required: false

  dry-run:
    description: >
      Simulate action - does not remove any packages (true/false) Default: false
    required: false

  log-level:
    description: >
      Log level (error/warn/info/debug) Default: info
    required: false

runs:
  using: node20
  main: dist/index.js
